### ISSUE TITLE
 TypeError: Cannot create a consistent method resolution order (MRO) for bases ABC, Module

### ISSUE THREAD

**Issue by DuloArpi** [hezheug/sparse-double-descent#1]
When trying to run the first example, the following error appears: 
 root@saa-l-pc:/home/user/sparse/sparse-double-descent# python main.py lottery --training_steps=160ep --lr=0.1 --milestone_steps=80ep,120ep --gamma=0.1 --rewinding_steps=1000it --de       fault_hparams=cifar_pytorch_resnet_18 --levels=30 --random_labels_fraction=0.2 --dataset_name=cifar10 --gpu=0 --fix_all_random_seeds=1
Traceback (most recent call last):
  File "/home/user/sparse/sparse-double-descent/main.py", line 13, in <module>
    from experiments import runner_registry
  File "/home/user/sparse/sparse-double-descent/experiments/runner_registry.py", line 7, in <module>
    from training.runner import TrainingRunner
  File "/home/user/sparse/sparse-double-descent/training/runner.py", line 9, in <module>
    from utils import shared_args
  File "/home/user/sparse/sparse-double-descent/utils/shared_args.py", line 10, in <module>
    import models.registry
  File "/home/user/sparse/sparse-double-descent/models/registry.py", line 12, in <module>
    from models import cifar_vgg, mnist_mlp, imagenet_resnet, cifar_pytorch_resnet, tinyimagenet_resnet
  File "/home/user/sparse/sparse-double-descent/models/cifar_vgg.py", line 10, in <module>
    from pruning import magnitude
  File "/home/user/sparse/sparse-double-descent/pruning/magnitude.py", line 10, in <module>
    import models.base
  File "/home/user/sparse/sparse-double-descent/models/base.py", line 127, in <module>
    class DistributedDataParallel(Model, torch.nn.parallel.DistributedDataParallel):
  File "/root/miniconda3/lib/python3.9/abc.py", line 106, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases ABC, Module

pytorch-1.12.1, torchvision-0.13.1, but the same with older packages.
Thank you in advance.

**Comment by he-zh** [comment]
Thanks for pointing out this issue!

Models are trained using DataParallel instead of DistributedDataParallel in all these examples. 
So simply commenting out the code from line 127 to line 156 in models/base.py will work.

I will figure out what causes this error and get back to you later.

**Comment by hezheug** [comment]
I switch the order of superclasses when defining the base class [Model](https://github.com/hezheug/sparse-double-descent/blob/f9bbdccab9d520ec40b8b9f051a7269b2cca8caa/models/base.py#L14) in models/base.py.
This error should be fixed now.

Thanks again for your feedback!

**Comment by he-zh** [comment]
I switch the order of superclasses when defining the base class [Model](https://github.com/hezheug/sparse-double-descent/blob/f9bbdccab9d520ec40b8b9f051a7269b2cca8caa/models/base.py#L14) in models/base.py.
This error should be fixed now.

Thanks again for your feedback!
